language: ruby

cache:
  bundler: true
  directories:
    - "spec/fixtures/puppet_controlrepo/.onceover" # Onceover cache

script: bundle exec rake full_tests
bundler_args: --path vendor/bundle

matrix:
  include:
    # 2017.3 -> 2018.1
    - rvm: 2.4.5
      env: PUPPET_VERSION="~>5.0"

    # 2019.0 -> 2019.8
    - rvm: 2.5.8
      env: PUPPET_VERSION="~>6.0"
    # 2021
    - rvm: 2.7.1
      env: PUPPET_VERSION="~>7.0"
